// Static products menu catalog seed data
export const products = [
  {
    "id": "mutton-marag",
    "name": "Mutton Marag",
    "price": "$7.99",
    "image": "/image%20copy%2013.png",
    "category": "Soups",
    "diet": "NON-VEG",
    "badge": "Weekend Special",
    "dietColor": "#dc2626",
    "desc": "A prized Hyderabadi delicacy — tender ribs stewed overnight in a milky spice-laced broth. Rich in collagen and slow-cooked with whole spices for a deeply warming bowl of heritage.",
    "spiceDefault": "Mild"
  },
  {
    "id": "sweet-corn-soup",
    "name": "Sweet Corn Soup",
    "price": "$4.99",
    "image": "/image%20copy%208.png",
    "category": "Soups",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Silky cream-style corn soup with a gentle hint of pepper — light, soothing, and satisfying. A restaurant classic that warms the soul without overwhelming the palate.",
    "spiceDefault": "Mild"
  },
  {
    "id": "veg-manchow",
    "name": "Veg Manchow",
    "price": "$4.99",
    "image": "/image%20copy%209.png",
    "category": "Soups",
    "diet": "VEG",
    "badge": "SOUPS",
    "dietColor": "#16a34a",
    "desc": "A tangy Indo-Chinese broth packed with crispy noodles, fresh vegetables, and a spicy punch. Every spoonful delivers a satisfying crunch.",
    "spiceDefault": "Medium"
  },
  {
    "id": "chicken-shorba",
    "name": "Chicken Shorba",
    "price": "$5.99",
    "image": "/image%20copy%2010.png",
    "category": "Soups",
    "diet": "NON-VEG",
    "badge": "NON-VEG",
    "dietColor": "#dc2626",
    "desc": "Aromatic slow-cooked chicken broth infused with whole spices, ginger, and fresh coriander. A Mughal-inspired soup that heals and delights.",
    "spiceDefault": "Mild"
  },
  {
    "id": "mutton-shorba",
    "name": "Mutton Shorba",
    "price": "$6.99",
    "image": "/image%20copy%2011.png",
    "category": "Soups",
    "diet": "NON-VEG",
    "badge": "NON-VEG",
    "dietColor": "#dc2626",
    "desc": "Rich bone-simmered mutton broth fragrant with cardamom and mace — a warming Mughal classic. Deeply nourishing and full of authentic character.",
    "spiceDefault": "Mild"
  },
  {
    "id": "mutton-paya",
    "name": "Mutton Paya",
    "price": "$6.99",
    "image": "/image%20copy%2012.png",
    "category": "Soups",
    "diet": "NON-VEG",
    "badge": "NON-VEG",
    "dietColor": "#dc2626",
    "desc": "Traditional slow-cooked trotters in a deeply spiced collagen-rich broth, best with fresh naan. A beloved Hyderabadi breakfast classic, served all day.",
    "spiceDefault": "Medium"
  },
  {
    "id": "veg-lollypop",
    "name": "Veg Lollypop",
    "price": "$15.99",
    "image": "/veg_lollypop_appetizer.png",
    "category": "Appetizers",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Crispy mixed-vegetable fritters on sticks, tossed in a tangy chili-garlic glaze. A plant-based party starter with bold Indo-Chinese flavors.",
    "spiceDefault": "Medium"
  },
  {
    "id": "chilli-paneer",
    "name": "Chilli Paneer / Mushroom",
    "price": "$15.99",
    "image": "/chilli_paneer_appetizer.png",
    "category": "Appetizers",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Wok-tossed with bell peppers and onions in a fiery Indo-Chinese soy-chili sauce. Available with paneer or mushroom — both equally irresistible.",
    "spiceDefault": "Hot"
  },
  {
    "id": "baby-corn-fritters",
    "name": "Baby Corn Fritters",
    "price": "$15.99",
    "image": "/baby_corn_fritters.png",
    "category": "Appetizers",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Lightly battered whole baby corn fried golden, served with a zesty dipping sauce. A crowd-pleasing appetizer with a satisfying crunch.",
    "spiceDefault": "Mild"
  },
  {
    "id": "bangla-paneer",
    "name": "Bangla Paneer",
    "price": "$15.99",
    "image": "/image%20copy%2020.png",
    "category": "Appetizers",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Cottage cheese tossed in a fragrant Bengali-spiced masala with mustard and green chili. A unique regional take on the beloved paneer starter.",
    "spiceDefault": "Medium"
  },
  {
    "id": "mushroom-duplex",
    "name": "Mushroom Duplex",
    "price": "$15.99",
    "image": "/image%20copy%2016.png",
    "category": "Appetizers",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Crispy fried mushrooms layered with two distinct spice profiles — a delightful textural contrast. A must-try for mushroom lovers who crave bold flavors.",
    "spiceDefault": "Medium"
  },
  {
    "id": "hara-bara-kabab",
    "name": "Hara Bara Kabab",
    "price": "$15.99",
    "image": "/image%20copy%2017.png",
    "category": "Appetizers",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Pan-seared spinach and pea patties with herbs and paneer — vibrant, light, and satisfying. A North Indian classic with a gorgeous green exterior.",
    "spiceDefault": "Mild"
  },
  {
    "id": "chicken-pepper-fry",
    "name": "Chicken Pepper Fry",
    "price": "$16.99",
    "image": "/image%20copy%2014.png",
    "category": "Appetizers",
    "diet": "NON-VEG",
    "badge": "Chicken",
    "dietColor": "#dc2626",
    "desc": "Bone-in chicken stir-fried with cracked pepper, curry leaves, and caramelized onions. A South Indian staple with intense, peppery heat.",
    "spiceDefault": "Hot"
  },
  {
    "id": "chilli-chicken-dry",
    "name": "Chilli Chicken Dry",
    "price": "$16.99",
    "image": "/image%20copy%2015.png",
    "category": "Appetizers",
    "diet": "NON-VEG",
    "badge": "Chicken",
    "dietColor": "#dc2626",
    "desc": "Crispy battered chicken tossed in a bold Indo-Chinese chili-soy reduction with spring onions. The perfect shareable starter for spice lovers.",
    "spiceDefault": "Hot"
  },
  {
    "id": "coriander-chicken",
    "name": "Coriander Chicken",
    "price": "$16.99",
    "image": "/signature_coriander_chicken.png",
    "category": "Appetizers",
    "diet": "NON-VEG",
    "badge": "Chicken",
    "dietColor": "#dc2626",
    "desc": "Tender chicken coated in a fresh green coriander marinade, pan-seared to perfection. Herbaceous, aromatic, and utterly distinctive in every bite.",
    "spiceDefault": "Medium"
  },
  {
    "id": "chicken-lollypop",
    "name": "Chicken Lollypop",
    "price": "$16.99",
    "image": "/image%20copy%2023.png",
    "category": "Appetizers",
    "diet": "NON-VEG",
    "badge": "Chicken",
    "dietColor": "#dc2626",
    "desc": "Frenched drumettes fried crisp and glazed in a sweet-spicy chili sauce — a crowd favorite. Great for sharing, impossible to stop eating.",
    "spiceDefault": "Hot"
  },
  {
    "id": "bangla-chicken",
    "name": "Bangla Chicken",
    "price": "$16.99",
    "image": "/Bangla%20Chicken.png",
    "category": "Appetizers",
    "diet": "NON-VEG",
    "badge": "Chicken",
    "dietColor": "#dc2626",
    "desc": "Bold Bengali-style chicken tossed with mustard seeds, panch phoron, and green chilies. A regional specialty with a complex, layered flavor profile.",
    "spiceDefault": "Medium"
  },
  {
    "id": "pachimirchi-chicken-65",
    "name": "Pachimirchi Chicken 65",
    "price": "$16.99",
    "image": "/chicken_65_appetizer.png",
    "category": "Appetizers",
    "diet": "NON-VEG",
    "badge": "Signature",
    "dietColor": "#b45309",
    "desc": "The Hyderabadi classic — fried chicken bites marinated in green chili paste and yogurt. Crispy, fiery, and packed with heritage flavors from the royal kitchens.",
    "spiceDefault": "Hot"
  },
  {
    "id": "chicken-555",
    "name": "Chicken 555",
    "price": "$16.99",
    "image": "/chicken_555.png",
    "category": "Appetizers",
    "diet": "NON-VEG",
    "badge": "Signature",
    "dietColor": "#b45309",
    "desc": "A Chettinad-inspired fiery dry fry with five-spice masala — bold heat, deep flavor. Named for its legendary combination of five signature spices.",
    "spiceDefault": "Extra Hot"
  },
  {
    "id": "mutton-pepper-fry",
    "name": "Mutton Pepper Fry",
    "price": "$17.99",
    "image": "/mutton_pepper_fry.png",
    "category": "Appetizers",
    "diet": "NON-VEG",
    "badge": "Mutton",
    "dietColor": "#dc2626",
    "desc": "Slow-cooked mutton pieces stir-fried with whole black pepper and aromatic curry leaves. A Chettinad specialty that pairs perfectly with parotta.",
    "spiceDefault": "Hot"
  },
  {
    "id": "mutton-ghee-roast",
    "name": "Mutton Ghee Roast",
    "price": "$17.99",
    "image": "/mutton_ghee_roast_appetizer.png",
    "category": "Appetizers",
    "diet": "NON-VEG",
    "badge": "SIGNATURE",
    "dietColor": "#b45309",
    "desc": "Mangalorean-style mutton slow-roasted in clarified butter with tangy tamarind-spice masala. A rich, indulgent dish with a cult following.",
    "spiceDefault": "Medium"
  },
  {
    "id": "pathar-ka-gosht",
    "name": "Pathar Ka Gosht",
    "price": "$17.99",
    "image": "/signature_pathar_la_gosh.png",
    "category": "Appetizers",
    "diet": "NON-VEG",
    "badge": "SIGNATURE",
    "dietColor": "#dc2626",
    "desc": "Hyderabadi tenderized lamb seared on a stone griddle with raw papaya marinade and spices. A royal Nizami delicacy cooked using an ancient technique for unparalleled tenderness.",
    "spiceDefault": "Medium"
  },
  {
    "id": "shrimp-loose",
    "name": "Shrimp Loose / Chilli",
    "price": "$16.99",
    "image": "/Shrimp%20Loose%20.png",
    "category": "Appetizers",
    "diet": "NON-VEG",
    "badge": "Seafood",
    "dietColor": "#2563eb",
    "desc": "Jumbo shrimp fried plain or tossed in a zesty chili-garlic sauce — your pick. Fresh, plump, and packed with coastal flavor.",
    "spiceDefault": "Medium"
  },
  {
    "id": "firecracker-shrimp",
    "name": "Firecracker Shrimp",
    "price": "$16.99",
    "image": "/firecracker_shrimp.png",
    "category": "Appetizers",
    "diet": "NON-VEG",
    "badge": "Seafood",
    "dietColor": "#2563eb",
    "desc": "Crispy shrimp in a bold sriracha-mayo glaze — explosive heat with a creamy finish. One of our most-ordered seafood starters.",
    "spiceDefault": "Hot"
  },
  {
    "id": "crab-stuffed-shrimp",
    "name": "Crab Stuffed Shrimp",
    "price": "$17.99",
    "image": "/crab_stuffed_shrimp_v2.png",
    "category": "Appetizers",
    "diet": "NON-VEG",
    "badge": "SIGNATURE",
    "dietColor": "#b45309",
    "desc": "Butterflied shrimp filled with spiced crab meat, lightly breaded and pan-seared golden. A luxurious seafood appetizer that combines two ocean favorites in one stunning bite.",
    "spiceDefault": "Medium"
  },
  {
    "id": "full-fish-tawa-fry",
    "name": "Full Fish Tawa Fry",
    "price": "$18.99",
    "image": "/image%20copy%2024.png",
    "category": "Appetizers",
    "diet": "NON-VEG",
    "badge": "SIGNATURE",
    "dietColor": "#b45309",
    "desc": "Whole fish marinated in coastal masala and seared on a cast-iron griddle to flaky perfection. A showstopper appetizer for true seafood enthusiasts.",
    "spiceDefault": "Medium"
  },
  {
    "id": "paneer-tikka",
    "name": "Paneer Tikka",
    "price": "$17.99",
    "image": "/image%20copy%2062.png",
    "category": "Tandoor",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Charred cottage cheese in your choice of Malai, Afghani, Tandoori, or Hariyali marinade. Four distinct flavor journeys from our clay oven.",
    "spiceDefault": "Medium"
  },
  {
    "id": "malai-broccoli",
    "name": "Malai Broccoli",
    "price": "$17.99",
    "image": "/malai_broccoli.png",
    "category": "Tandoor",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Tender broccoli florets marinated in cream and mild spices, gently roasted in the tandoor. A light, elegant option that elevates humble broccoli to something extraordinary.",
    "spiceDefault": "Mild"
  },
  {
    "id": "kalmi-kebab",
    "name": "Kalmi Kebab",
    "price": "$17.99",
    "image": "/image%20copy%2022.png",
    "category": "Tandoor",
    "diet": "NON-VEG",
    "badge": "NON-VEG",
    "dietColor": "#dc2626",
    "desc": "Juicy whole chicken legs marinated in a cream-yogurt spice blend and slow-roasted in clay. Falling-off-the-bone tender with a gorgeous charred exterior.",
    "spiceDefault": "Medium"
  },
  {
    "id": "habibi-hara-wings",
    "name": "Habibi Hara Wings",
    "price": "$17.99",
    "image": "/tandoori_wings.png",
    "category": "Tandoor",
    "diet": "NON-VEG",
    "badge": "Signature",
    "dietColor": "#b45309",
    "desc": "Tandoor-roasted wings in a vibrant green herb-chili marinade — aromatic, smoky, and addictive. A Middle Eastern–inspired creation exclusive to ALMAS.",
    "spiceDefault": "Hot"
  },
  {
    "id": "tandoori-chicken",
    "name": "Tandoori Chicken",
    "price": "$17.99",
    "image": "/menu%20list%20images/image%20copy%202.png",
    "category": "Tandoor",
    "diet": "NON-VEG",
    "badge": "NON-VEG",
    "dietColor": "#dc2626",
    "desc": "The timeless classic — chicken on bone in a red chili-yogurt marinade, charred in a clay oven. Every bite carries the smoky soul of traditional Indian cooking.",
    "spiceDefault": "Medium"
  },
  {
    "id": "zaatar-laymoun-tangdi",
    "name": "Zaatar Laymoun Tangdi (5 pcs)",
    "price": "$17.99",
    "image": "/lemon_tangdi.png",
    "category": "Tandoor",
    "diet": "NON-VEG",
    "badge": "Signature",
    "dietColor": "#b45309",
    "desc": "Lebanese za'atar and lemon drumsticks roasted golden in the tandoor — bright and herbaceous. A beautiful East-meets-West fusion from our ALMAS kitchen.",
    "spiceDefault": "Mild"
  },
  {
    "id": "chicken-shish-tawook",
    "name": "Chicken Shish Tawook",
    "price": "$17.99",
    "image": "/image%20copy%2044.png",
    "category": "Tandoor",
    "diet": "NON-VEG",
    "badge": "NON-VEG",
    "dietColor": "#dc2626",
    "desc": "Lebanese-style boneless chicken skewers in Malai, Afghani, or Tandoori marinade — smoky and succulent. A classic Lebanese preparation perfected in our clay oven.",
    "spiceDefault": "Medium"
  },
  {
    "id": "grill-chicken",
    "name": "Grill Chicken (Whole Bird)",
    "price": "$18.99 / $29.99",
    "image": "/grill_chicken_whole.png",
    "category": "Tandoor",
    "diet": "NON-VEG",
    "badge": "SIGNATURE",
    "dietColor": "#b45309",
    "desc": "A whole chicken split and slow-grilled over open flame — a showstopper for the table. Available as half or full bird, marinated in our signature spice blend. The undisputed star of our grill section.",
    "spiceDefault": "Medium"
  },
  {
    "id": "tandoor-full-fish",
    "name": "Tandoor Full Fish",
    "price": "$19.99",
    "image": "/signature_tandoori_fish.jpg",
    "category": "Tandoor",
    "diet": "NON-VEG",
    "badge": "Signature",
    "dietColor": "#b45309",
    "desc": "Whole fish marinated in a coastal spice blend and roasted in the clay oven to smoky perfection. Each fish is hand-scored and infused with our proprietary tandoor masala for maximum flavor penetration.",
    "spiceDefault": "Medium"
  },
  {
    "id": "tandoor-family-platter",
    "name": "Tandoor Family Platter",
    "price": "$49.99",
    "image": "/image%20copy%2045.png",
    "category": "Tandoor",
    "diet": "NON-VEG",
    "badge": "SERVES 4+",
    "dietColor": "#7c3aed",
    "desc": "4 Tangdi Kebab, 2 Tandoori Chicken, 3 Afghani & Chicken Tikka, 1 Full Fish — a feast from the clay oven. The ultimate sharing platter for family gatherings and celebrations.",
    "spiceDefault": "Medium"
  },
  {
    "id": "lasooni-dal-tadka",
    "name": "Lasooni Dal Tadka",
    "price": "$15.99",
    "image": "/lasooni_dal_tadka.png",
    "category": "Mains",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Yellow lentils finished with a sizzling garlic-infused tarka and smoky chili butter. A comforting Indian staple elevated to restaurant quality.",
    "spiceDefault": "Medium"
  },
  {
    "id": "dal-makhani",
    "name": "Dal Makhani",
    "price": "$15.99",
    "image": "/image%20copy%2047.png",
    "category": "Mains",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Black lentils slow-cooked overnight with butter and cream — rich, smoky, deeply comforting. A Punjab classic that has earned its place on every great Indian menu.",
    "spiceDefault": "Mild"
  },
  {
    "id": "paneer-butter-masala",
    "name": "Paneer Butter Masala",
    "price": "$16.99",
    "image": "/image%20copy%2062.png",
    "category": "Mains",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Soft cottage cheese in a velvety tomato-butter sauce — mildly spiced and utterly indulgent. A universal favorite that never disappoints.",
    "spiceDefault": "Mild"
  },
  {
    "id": "okra-double-double",
    "name": "Okra Double Double",
    "price": "$15.99",
    "image": "/okra_double_double.png",
    "category": "Mains",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Crispy-fried okra tossed in a tangy onion-tomato masala with a double hit of spice. A uniquely satisfying vegetarian dish with great texture and bold flavor.",
    "spiceDefault": "Hot"
  },
  {
    "id": "butter-chicken",
    "name": "Butter Chicken",
    "price": "$16.99",
    "image": "/image%20copy%2046.png",
    "category": "Mains",
    "diet": "NON-VEG",
    "badge": "CLASSIC",
    "dietColor": "#dc2626",
    "desc": "Tandoori chicken in a silky fenugreek-tomato cream sauce — the beloved Indian classic. Rich, buttery, and perfectly balanced between heat and sweetness.",
    "spiceDefault": "Medium"
  },
  {
    "id": "chicken-makhani",
    "name": "Chicken Makhani",
    "price": "$16.99",
    "image": "/chicken_makhani.png",
    "category": "Mains",
    "diet": "NON-VEG",
    "badge": "PREMIUM",
    "dietColor": "#dc2626",
    "desc": "A richer, spice-forward take on butter chicken with a deeper tomato-butter base. For those who prefer a bolder, more intensely flavored version of the classic.",
    "spiceDefault": "Medium"
  },
  {
    "id": "dum-ka-murgh",
    "name": "Dum ka Murgh",
    "price": "$16.99",
    "image": "/dum_ka_murgh.png",
    "category": "Mains",
    "diet": "NON-VEG",
    "badge": "NON-VEG",
    "dietColor": "#dc2626",
    "desc": "Chicken slow-sealed in a pot to trap all aromatics — tender, fragrant, and deeply flavorful. An ancient Hyderabadi technique that produces extraordinarily tender results.",
    "spiceDefault": "Medium"
  },
  {
    "id": "almas-spl-chicken",
    "name": "Almas Spl Chicken (Laal Maas)",
    "price": "$17.99",
    "image": "/image%20copy%2049.png",
    "category": "Mains",
    "diet": "NON-VEG",
    "badge": "SIGNATURE",
    "dietColor": "#b45309",
    "desc": "A royal Rajasthani red-chili chicken curry, fiery and rich with whole dried chilies and ghee. One of the most requested specials on our menu — not for the faint-hearted.",
    "spiceDefault": "Extra Hot"
  },
  {
    "id": "hyderabadi-mutton-curry",
    "name": "Hyderabadi Mutton Curry",
    "price": "$17.99",
    "image": "/image%20copy%2050.png",
    "category": "Mains",
    "diet": "NON-VEG",
    "badge": "MUTTON",
    "dietColor": "#dc2626",
    "desc": "Bone-in mutton in a rustic spiced Hyderabadi gravy — bold, hearty, and full of depth. A recipe passed down through generations of Hyderabadi cooks.",
    "spiceDefault": "Hot"
  },
  {
    "id": "dum-ka-mutton",
    "name": "Dum ka Mutton",
    "price": "$17.99",
    "image": "/image%20copy%2052.png",
    "category": "Mains",
    "diet": "NON-VEG",
    "badge": "MUTTON",
    "dietColor": "#dc2626",
    "desc": "Slow-sealed mutton with aromatic whole spices — cooked in its own steam for tenderness. A patience-rewarding slow-cook that produces melt-in-the-mouth results.",
    "spiceDefault": "Medium"
  },
  {
    "id": "mutton-kheema-masala",
    "name": "Mutton Kheema Masala",
    "price": "$17.99",
    "image": "/image%20copy%2051.png",
    "category": "Mains",
    "diet": "NON-VEG",
    "badge": "MUTTON",
    "dietColor": "#dc2626",
    "desc": "Spiced minced mutton cooked with peas, tomatoes, and garam masala — rustic and hearty. A comforting everyday preparation elevated with premium quality mutton.",
    "spiceDefault": "Medium"
  },
  {
    "id": "fish-pulusu",
    "name": "Fish Pulusu",
    "price": "$17.99",
    "image": "/fish_pulusu_mains.png",
    "category": "Mains",
    "diet": "NON-VEG",
    "badge": "SEAFOOD",
    "dietColor": "#2563eb",
    "desc": "Andhra-style fish curry in a tamarind and raw mango broth — tangy, spicy, and comforting. A fiery coastal classic that pairs beautifully with steamed rice.",
    "spiceDefault": "Hot"
  },
  {
    "id": "almas-spl-fish-curry",
    "name": "Almas Spl Fish Curry",
    "price": "$17.99",
    "image": "/image%20copy%2053.png",
    "category": "Mains",
    "diet": "NON-VEG",
    "badge": "SIGNATURE",
    "dietColor": "#b45309",
    "desc": "Chef's special fish curry — a rich coastal masala with secret spice blends. Our most closely guarded recipe, developed over years of culinary refinement.",
    "spiceDefault": "Medium"
  },
  {
    "id": "chicken-dum-biryani",
    "name": "Chicken Dum Biryani",
    "price": "$14.99",
    "image": "/chicken_dum_biryani_premium.png",
    "category": "Biryani",
    "diet": "NON-VEG",
    "badge": "CLASSIC",
    "dietColor": "#dc2626",
    "desc": "Classic bone-in chicken sealed in dum with saffron basmati, rose water, and caramelized onions. Every grain of rice tells the story of slow, patient cooking.",
    "spiceDefault": "Medium"
  },
  {
    "id": "almas-spl-chicken-biryani",
    "name": "Almas Spl Chicken Biryani",
    "price": "$16.99",
    "image": "/hero_biryani_premium_1776972575156.png",
    "category": "Biryani",
    "diet": "NON-VEG",
    "badge": "SIGNATURE",
    "dietColor": "#b45309",
    "desc": "Chef's secret masala blend that has made this biryani legendary among our regulars. The most-ordered item on our menu — a must-try for every first-time visitor.",
    "spiceDefault": "Medium"
  },
  {
    "id": "mutton-dum-biryani",
    "name": "Mutton Dum Biryani",
    "price": "$16.99",
    "image": "/mutton_dum_biryani_premium.png",
    "category": "Biryani",
    "diet": "NON-VEG",
    "badge": "CLASSIC",
    "dietColor": "#dc2626",
    "desc": "Tender mutton slow-sealed with aromatic whole spices and saffron-infused long-grain rice. A Hyderabadi classic prepared with the same reverence as it was in the Nizam's court.",
    "spiceDefault": "Medium"
  },
  {
    "id": "lamb-shank-biryani",
    "name": "Lamb Shank Biryani",
    "price": "$20.99",
    "image": "/lamb_shank_biryani_premium.png",
    "category": "Biryani",
    "diet": "NON-VEG",
    "badge": "SIGNATURE",
    "dietColor": "#b45309",
    "desc": "A crown jewel — a slow-braised whole lamb shank resting atop a bed of premium saffron biryani. Our most dramatic presentation, reserved for those who demand the very best.",
    "spiceDefault": "Medium"
  },
  {
    "id": "chicken-alfaham-mandi",
    "name": "Chicken Alfaham Mandi",
    "price": "$16.99 / $24.99 / $32.99",
    "image": "/chicken_mandi_signature.png",
    "category": "Mandi",
    "diet": "NON-VEG",
    "badge": "SIGNATURE",
    "dietColor": "#b45309",
    "desc": "Arabic charcoal-grilled chicken slow-roasted over Mandi rice — a Middle Eastern showpiece. Available for 1, 2, or 3 people. The crown jewel of our Arabian-inspired Mandi menu.",
    "spiceDefault": "Medium"
  },
  {
    "id": "grill-chicken-mandi",
    "name": "Grill Chicken Mandi",
    "price": "$19.99 / $36.99 / $53.99",
    "image": "/signature_grill_chicken.jpg",
    "category": "Mandi",
    "diet": "NON-VEG",
    "badge": "FEAST",
    "dietColor": "#dc2626",
    "desc": "Half or whole open-flame grilled chicken over fragrant Mandi rice — a feast for the table. Served for 1, 2, or 3 people with traditional Mandi accompaniments.",
    "spiceDefault": "Medium"
  },
  {
    "id": "lamb-shank-mandi",
    "name": "Lamb Shank Mandi",
    "price": "$21.99 / $39.99 / $57.99",
    "image": "/lamb_shank_biryani_premium.png",
    "category": "Mandi",
    "diet": "NON-VEG",
    "badge": "SIGNATURE",
    "dietColor": "#b45309",
    "desc": "A whole slow-roasted lamb shank, meltingly tender, presented over a generous Mandi rice bed. The most impressive sharing dish on our menu — ideal for celebrations.",
    "spiceDefault": "Medium"
  },
  {
    "id": "cashew-paneer-pulao",
    "name": "Cashew Paneer Pulao",
    "price": "$16.99",
    "image": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=1974&auto=format&fit=crop",
    "category": "Pulao",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Basmati rice cooked with golden-fried paneer and whole cashews in a delicate whole-spice broth.",
    "spiceDefault": "Mild"
  },
  {
    "id": "mushroom-pulao",
    "name": "Mushroom Pulao",
    "price": "$16.99",
    "image": "/image%20copy%2072.png",
    "category": "Pulao",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Earthy button mushrooms sauteed with aromatics and folded into fragrant long-grain basmati.",
    "spiceDefault": "Mild"
  },
  {
    "id": "baigan-pulao",
    "name": "Baigan Pulao",
    "price": "$16.99",
    "image": "https://images.unsplash.com/photo-1516714435131-44d6b64dc6a2?q=80&w=2070&auto=format&fit=crop",
    "category": "Pulao",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Smoky roasted eggplant layered into spiced pulao — a humble yet deeply flavorful combination.",
    "spiceDefault": "Mild"
  },
  {
    "id": "chicken-ghee-roast-pulao",
    "name": "Chicken Ghee Roast Pulao",
    "price": "$16.99",
    "image": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?q=80&w=1931&auto=format&fit=crop",
    "category": "Pulao",
    "diet": "NON-VEG",
    "badge": "NON-VEG",
    "dietColor": "#dc2626",
    "desc": "Mangalorean ghee-roast chicken tossed through aromatic rice — tangy, buttery, and bold.",
    "spiceDefault": "Medium"
  },
  {
    "id": "telangana-kura-kodi-pulao",
    "name": "Telangana Kura Kodi Pulao",
    "price": "$16.99",
    "image": "/image%20copy%2075.png",
    "category": "Pulao",
    "diet": "NON-VEG",
    "badge": "SIGNATURE",
    "dietColor": "#b45309",
    "desc": "Rustic Telangana-style chicken curry rice — cooked together for a bold one-pot country feast.",
    "spiceDefault": "Hot"
  },
  {
    "id": "mutton-sukka-pulao",
    "name": "Mutton Sukka Pulao",
    "price": "$17.99",
    "image": "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=2069&auto=format&fit=crop",
    "category": "Pulao",
    "diet": "NON-VEG",
    "badge": "MUTTON",
    "dietColor": "#dc2626",
    "desc": "Dry-style spiced mutton sukka tossed through fragrant basmati — hearty and intensely flavored.",
    "spiceDefault": "Hot"
  },
  {
    "id": "mutton-roast-pulao",
    "name": "Mutton Roast Pulao",
    "price": "$17.99",
    "image": "https://images.unsplash.com/photo-1606491956689-2ea866880c84?q=80&w=1921&auto=format&fit=crop",
    "category": "Pulao",
    "diet": "NON-VEG",
    "badge": "MUTTON",
    "dietColor": "#dc2626",
    "desc": "Slow-roasted mutton pieces folded into long-grain rice with caramelized onions and whole spices.",
    "spiceDefault": "Medium"
  },
  {
    "id": "chepa-pulao",
    "name": "Chepa Pulao",
    "price": "$17.99",
    "image": "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=1974&auto=format&fit=crop",
    "category": "Pulao",
    "diet": "NON-VEG",
    "badge": "SEAFOOD",
    "dietColor": "#2563eb",
    "desc": "Andhra-style fish pulao — spiced fish pieces cooked into tamarind-tinged fragrant rice.",
    "spiceDefault": "Medium"
  },
  {
    "id": "royyala-vepudu-pulao",
    "name": "Royyala Vepudu Pulao",
    "price": "$17.99",
    "image": "/image%20copy%2073.png",
    "category": "Pulao",
    "diet": "NON-VEG",
    "badge": "SEAFOOD",
    "dietColor": "#2563eb",
    "desc": "Fiery Andhra shrimp fry nestled in long-grain rice — bold, spicy, and deeply coastal.",
    "spiceDefault": "Hot"
  },
  {
    "id": "fried-rice",
    "name": "Fried Rice",
    "price": "Veg $13.99 / Chicken $14.99 / Shrimp $15.99",
    "image": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?q=80&w=1925&auto=format&fit=crop",
    "category": "Chinese",
    "diet": "NON-VEG",
    "badge": "WOK SPECIAL",
    "dietColor": "#b45309",
    "desc": "Wok-tossed basmati with egg, vegetables, and soy sauce — light, quick, and satisfying.",
    "spiceDefault": "Mild"
  },
  {
    "id": "schezwan-fried-rice",
    "name": "Schezwan Fried Rice",
    "price": "Veg $14.99 / Chicken $15.99 / Shrimp $16.99",
    "image": "https://images.unsplash.com/photo-1585032226651-759b368d7246?q=80&w=1918&auto=format&fit=crop",
    "category": "Chinese",
    "diet": "NON-VEG",
    "badge": "BOLD & SPICY",
    "dietColor": "#dc2626",
    "desc": "The beloved fried rice kicked up with bold Schezwan chili sauce — fiery and addictive.",
    "spiceDefault": "Hot"
  },
  {
    "id": "hakka-noodles",
    "name": "Hakka Noodles",
    "price": "Veg $13.99 / Chicken $14.99 / Shrimp $15.99",
    "image": "https://images.unsplash.com/photo-1552611052-33e04de081de?q=80&w=1964&auto=format&fit=crop",
    "category": "Chinese",
    "diet": "NON-VEG",
    "badge": "CLASSIC",
    "dietColor": "#b45309",
    "desc": "Thin noodles stir-fried with vegetables and soy sauce in your choice of protein.",
    "spiceDefault": "Mild"
  },
  {
    "id": "schezwan-hakka-noodles",
    "name": "Schezwan Hakka Noodles",
    "price": "Veg $14.99 / Chicken $15.99 / Shrimp $16.99",
    "image": "https://images.unsplash.com/photo-1552611052-33e04de081de?q=80&w=1964&auto=format&fit=crop",
    "category": "Chinese",
    "diet": "NON-VEG",
    "badge": "SMOKY & SPICY",
    "dietColor": "#dc2626",
    "desc": "Hakka noodles elevated with a spicy Schezwan sauce for a bold, smoky wok finish.",
    "spiceDefault": "Hot"
  },
  {
    "id": "vegetable-momo",
    "name": "Vegetable Momo",
    "price": "$12.99",
    "image": "/vegetable_momo.png",
    "category": "Momo",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Delicate steamed dumplings filled with spiced vegetables, in Malai, Tandoori, or Hariyali style.",
    "spiceDefault": "Medium"
  },
  {
    "id": "chicken-momo",
    "name": "Chicken Momo",
    "price": "$13.99",
    "image": "/chicken_momo.png",
    "category": "Momo",
    "diet": "NON-VEG",
    "badge": "NON-VEG",
    "dietColor": "#dc2626",
    "desc": "Juicy chicken-filled dumplings in your choice of Malai, Tandoori, or Hariyali marinade.",
    "spiceDefault": "Medium"
  },
  {
    "id": "butter-naan",
    "name": "Butter Naan",
    "price": "$3.99",
    "image": "/image%20copy%2069.png",
    "category": "Breads",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Classic tandoor-baked flatbread glazed with rich melted butter.",
    "spiceDefault": "Mild"
  },
  {
    "id": "garlic-naan",
    "name": "Garlic Naan",
    "price": "$4.99",
    "image": "https://images.unsplash.com/photo-1573140401552-3fab0b24306f?q=80&w=2070&auto=format&fit=crop",
    "category": "Breads",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Tandoori flatbread topped with minced garlic, fresh cilantro, and melted butter.",
    "spiceDefault": "Mild"
  },
  {
    "id": "bullet-naan",
    "name": "Bullet Naan",
    "price": "$4.99",
    "image": "/image%20copy%2070.png",
    "category": "Breads",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Fiery tandoori flatbread topped with chopped green chilies, cilantro, and warm ghee.",
    "spiceDefault": "Hot"
  },
  {
    "id": "tandoori-roti",
    "name": "Tandoori Roti",
    "price": "$2.99",
    "image": "/image%20copy%2071.png",
    "category": "Breads",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Rustic whole-wheat flatbread baked to crisp perfection in our clay oven.",
    "spiceDefault": "Mild"
  },
  {
    "id": "irani-chai-bun-maska",
    "name": "Irani Chai & Bun Maska",
    "price": "$9.99",
    "image": "/signature_irani_chai.png",
    "category": "Beverages",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "The iconic Hyderabadi café pairing — a cup of creamy Irani chai with a buttered bun. A beloved ritual in every Hyderabadi's life, now available at ALMAS. Simple, timeless, perfect.",
    "spiceDefault": "Mild"
  },
  {
    "id": "qubani-ka-meetha",
    "name": "Qubani Ka Meetha",
    "price": "$7.99",
    "image": "/image%20copy%2074.png",
    "category": "Desserts",
    "diet": "VEG",
    "badge": "Hyderabadi Classic",
    "dietColor": "#b45309",
    "desc": "Traditional stewed apricot dessert, served with fresh cream.",
    "spiceDefault": "Mild"
  },
  {
    "id": "apricot-delight",
    "name": "Apricot Delight",
    "price": "$8.99",
    "image": "/image%20copy%2076.png",
    "category": "Desserts",
    "diet": "VEG",
    "badge": "Signature",
    "dietColor": "#b45309",
    "desc": "Layers of apricot compote, moist sponge, and fresh cream.",
    "spiceDefault": "Mild"
  },
  {
    "id": "mango-lassi",
    "name": "Mango Lassi",
    "price": "$5.99",
    "image": "https://images.unsplash.com/photo-1546173159-315724a31696?q=80&w=1974&auto=format&fit=crop",
    "category": "Desserts",
    "diet": "VEG",
    "badge": "Refreshing",
    "dietColor": "#16a34a",
    "desc": "Silky yogurt blend with premium Alphonso mango pulp.",
    "spiceDefault": "Mild"
  },
  {
    "id": "almas-special-falooda",
    "name": "Almas Special Falooda",
    "price": "$8.99",
    "image": "/image%20copy%2077.png",
    "category": "Desserts",
    "diet": "VEG",
    "badge": "House Special",
    "dietColor": "#b45309",
    "desc": "Vermicelli, basil seeds, kulfi, and rose syrup topped with nuts.",
    "spiceDefault": "Mild"
  },
  {
    "id": "fish-chips",
    "name": "Fish Chips",
    "price": "Seafood",
    "image": "/Fish%20chips.png",
    "category": "Appetizers",
    "diet": "SEAFOOD",
    "badge": "Seafood",
    "dietColor": "#2563eb",
    "desc": "Golden spiced fish fillets with house-seasoned fries — a comfort classic, elevated.",
    "spiceDefault": "Medium"
  },
  {
    "id": "masala-fish-strips",
    "name": "Masala Fish Strips",
    "price": "Seafood",
    "image": "/Masala%20Fish%20Strips.png",
    "category": "Appetizers",
    "diet": "SEAFOOD",
    "badge": "Seafood",
    "dietColor": "#2563eb",
    "desc": "Tender fish strips coated in a tangy South Indian spice crust, fried to a crispy finish.",
    "spiceDefault": "Medium"
  },
  {
    "id": "paneer-tikka-masala",
    "name": "Paneer Tikka Masala",
    "price": "VEG",
    "image": "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=1974&auto=format&fit=crop",
    "category": "Mains",
    "diet": "VEG",
    "badge": "",
    "dietColor": "#16a34a",
    "desc": "Grilled paneer tikka simmered in a bold smoky masala — twice the flavor, twice the satisfaction.",
    "spiceDefault": "Medium"
  },
  {
    "id": "mix-veg-veg-kolhapuri",
    "name": "Mix Veg / Veg Kolhapuri",
    "price": "VEG",
    "image": "/image%20copy%2047.png",
    "category": "Mains",
    "diet": "VEG",
    "badge": "",
    "dietColor": "#16a34a",
    "desc": "Seasonal vegetables in a mild curry or a fiery Kolhapuri coconut-spice sauce.",
    "spiceDefault": "Medium"
  },
  {
    "id": "kadai-chicken",
    "name": "Kadai Chicken",
    "price": "NON-VEG",
    "image": "/image%20copy%2048.png",
    "category": "Mains",
    "diet": "NON-VEG",
    "badge": "",
    "dietColor": "#dc2626",
    "desc": "Chicken stir-cooked in a traditional wok with bell peppers, tomatoes, and coarse kadai spices.",
    "spiceDefault": "Medium"
  },
  {
    "id": "hyderabadi-chicken-curry",
    "name": "Hyderabadi Chicken Curry",
    "price": "HOT & SPICY",
    "image": "/image%20copy%2050.png",
    "category": "Mains",
    "diet": "NON-VEG",
    "badge": "HOT & SPICY",
    "dietColor": "#dc2626",
    "desc": "A fiery Hyderabadi-style curry with whole spices and bold heat — not for the faint-hearted.",
    "spiceDefault": "Medium"
  },
  {
    "id": "shrimp-goan-curry",
    "name": "Shrimp Goan Curry",
    "price": "SEAFOOD",
    "image": "/image%20copy%2054.png",
    "category": "Mains",
    "diet": "SEAFOOD",
    "badge": "",
    "dietColor": "#2563eb",
    "desc": "Plump shrimp simmered in a tangy coconut-Goan masala with red chilies and kokum.",
    "spiceDefault": "Medium"
  },
  {
    "id": "veg-cocktail-biryani",
    "name": "Veg Cocktail Biryani",
    "price": "VEG",
    "image": "/image%20copy%2058.png",
    "category": "Biryani",
    "diet": "VEG",
    "badge": "",
    "dietColor": "#16a34a",
    "desc": "Fragrant basmati layered with seasonal vegetables, saffron, and fried onions — light yet aromatic.",
    "spiceDefault": "Medium"
  },
  {
    "id": "paneer-biryani-65-pachimirchi-",
    "name": "Paneer Biryani (65 / Pachimirchi)",
    "price": "VEG",
    "image": "/image%20copy%2057.png",
    "category": "Biryani",
    "diet": "VEG",
    "badge": "",
    "dietColor": "#16a34a",
    "desc": "Long-grain rice dum-cooked with spiced paneer 65 or green chili paneer.",
    "spiceDefault": "Medium"
  },
  {
    "id": "chicken-fry-piece-biryani",
    "name": "Chicken Fry Piece Biryani",
    "price": "NON-VEG",
    "image": "/image%20copy%2055.png",
    "category": "Biryani",
    "diet": "NON-VEG",
    "badge": "",
    "dietColor": "#dc2626",
    "desc": "Crispy fried chicken pieces layered into biryani for extra texture and smoky depth.",
    "spiceDefault": "Medium"
  },
  {
    "id": "mutton-ghee-roast-biryani",
    "name": "Mutton Ghee Roast Biryani",
    "price": "SIGNATURE",
    "image": "/image%20copy%2059.png",
    "category": "Biryani",
    "diet": "NON-VEG",
    "badge": "SIGNATURE",
    "dietColor": "#dc2626",
    "desc": "Mangalorean ghee-roast mutton layered into biryani — a glorious fusion of two classics.",
    "spiceDefault": "Medium"
  },
  {
    "id": "mutton-fry-piece-biryani",
    "name": "Mutton Fry Piece Biryani",
    "price": "NON-VEG",
    "image": "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=2069&auto=format&fit=crop",
    "category": "Biryani",
    "diet": "NON-VEG",
    "badge": "",
    "dietColor": "#dc2626",
    "desc": "Golden fried mutton pieces nested in saffron basmati for a satisfying crunch with every bite.",
    "spiceDefault": "Medium"
  },
  {
    "id": "mutton-kheema-biryani",
    "name": "Mutton Kheema Biryani",
    "price": "NON-VEG",
    "image": "/image%20copy%2060.png",
    "category": "Biryani",
    "diet": "NON-VEG",
    "badge": "",
    "dietColor": "#dc2626",
    "desc": "Spiced minced mutton woven through fragrant rice — earthy, rich, and deeply satisfying.",
    "spiceDefault": "Medium"
  },
  {
    "id": "almas-spl-mutton-biryani",
    "name": "Almas Spl Mutton Biryani",
    "price": "SIGNATURE",
    "image": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=1974&auto=format&fit=crop",
    "category": "Biryani",
    "diet": "NON-VEG",
    "badge": "SIGNATURE",
    "dietColor": "#dc2626",
    "desc": "The pinnacle of our biryani menu — mutton in a chef-exclusive masala, slow and perfected.",
    "spiceDefault": "Medium"
  },
  {
    "id": "malai-kofta-mandi",
    "name": "Malai Kofta Mandi",
    "price": "$14.99 / $22.99 / $30.99",
    "image": "/image%20copy%2063.png",
    "category": "Mandi",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Cream-filled vegetable dumplings over aromatic Mandi rice — indulgent and beautifully spiced.",
    "spiceDefault": "Medium"
  },
  {
    "id": "soya-chaap-mandi",
    "name": "Soya Chaap Mandi",
    "price": "$14.99 / $22.99 / $30.99",
    "image": "/image%20copy%2067.png",
    "category": "Mandi",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Marinated soya chaap grilled and plated over fragrant Mandi rice with Yemeni spice blend.",
    "spiceDefault": "Medium"
  },
  {
    "id": "egg-plant-mandi",
    "name": "Egg Plant Mandi",
    "price": "$13.99 / $21.99 / $29.99",
    "image": "https://images.unsplash.com/photo-1626777552726-4a6b52c67ebf?q=80&w=2070&auto=format&fit=crop",
    "category": "Mandi",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Smoky roasted aubergine seasoned with Middle Eastern spices atop slow-cooked dum rice.",
    "spiceDefault": "Medium"
  },
  {
    "id": "paneer-tikka-mandi",
    "name": "Paneer Tikka Mandi",
    "price": "$15.99 / $23.99 / $31.99",
    "image": "/image%20copy%2062.png",
    "category": "Mandi",
    "diet": "VEG",
    "badge": "VEG",
    "dietColor": "#16a34a",
    "desc": "Tandoor-kissed paneer tikka (Malai / Tandoori / Hariyali) over Mandi rice.",
    "spiceDefault": "Medium"
  },
  {
    "id": "egg-roast-mandi",
    "name": "Egg Roast Mandi",
    "price": "$13.99 / $21.99 / $29.99",
    "image": "/image%20copy%2064.png",
    "category": "Mandi",
    "diet": "NON-VEG",
    "badge": "",
    "dietColor": "#dc2626",
    "desc": "Spiced roasted eggs nestled on Mandi rice — simple, hearty, and full of flavor.",
    "spiceDefault": "Medium"
  },
  {
    "id": "chicken-fry-piece-mandi",
    "name": "Chicken Fry Piece Mandi",
    "price": "$15.99 / $23.99 / $31.99",
    "image": "/image%20copy%2065.png",
    "category": "Mandi",
    "diet": "NON-VEG",
    "badge": "",
    "dietColor": "#dc2626",
    "desc": "Crispy fried chicken pieces served over aromatic Mandi rice with golden fried onions.",
    "spiceDefault": "Medium"
  },
  {
    "id": "chicken-broaster-mandi",
    "name": "Chicken Broaster Mandi",
    "price": "$16.99 / $24.99 / $32.99",
    "image": "/image%20copy%2066.png",
    "category": "Mandi",
    "diet": "NON-VEG",
    "badge": "CRISPY",
    "dietColor": "#dc2626",
    "desc": "Pressure-fried broaster chicken — ultra-crispy outside, juicy inside — on Mandi rice.",
    "spiceDefault": "Medium"
  },
  {
    "id": "chicken-tandoori-mandi",
    "name": "Chicken Tandoori Mandi",
    "price": "$16.99 / $24.99 / $32.99",
    "image": "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=2070&auto=format&fit=crop",
    "category": "Mandi",
    "diet": "NON-VEG",
    "badge": "SMOKY",
    "dietColor": "#dc2626",
    "desc": "Clay-oven roasted chicken with smoky spice crust served atop slow-cooked Mandi rice.",
    "spiceDefault": "Medium"
  },
  {
    "id": "mutton-juicy-mandi",
    "name": "Mutton Juicy Mandi",
    "price": "$17.99 / $26.99 / $35.99",
    "image": "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=2070&auto=format&fit=crop",
    "category": "Mandi",
    "diet": "NON-VEG",
    "badge": "TENDER",
    "dietColor": "#dc2626",
    "desc": "Slow-braised mutton pieces fall-off-the-bone tender, rested on saffron Mandi rice.",
    "spiceDefault": "Medium"
  },
  {
    "id": "mutton-fry-piece-mandi",
    "name": "Mutton Fry Piece Mandi",
    "price": "$17.99 / $26.99 / $35.99",
    "image": "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=2069&auto=format&fit=crop",
    "category": "Mandi",
    "diet": "NON-VEG",
    "badge": "MUTTON",
    "dietColor": "#dc2626",
    "desc": "Crispy-edged fried mutton served over Mandi rice with house spiced tomato sauce.",
    "spiceDefault": "Medium"
  },
  {
    "id": "mutton-ghee-roast-mandi",
    "name": "Mutton Ghee Roast Mandi",
    "price": "$19.99 / $29.99 / $39.99",
    "image": "https://images.unsplash.com/photo-1606491956689-2ea866880c84?q=80&w=1921&auto=format&fit=crop",
    "category": "Mandi",
    "diet": "NON-VEG",
    "badge": "SIGNATURE",
    "dietColor": "#dc2626",
    "desc": "Mangalorean ghee-roast mutton — tangy, buttery, and bold — served over Mandi rice.",
    "spiceDefault": "Medium"
  },
  {
    "id": "full-fish-tawa-fry-mandi",
    "name": "Full Fish Tawa Fry Mandi",
    "price": "$17.99 / $25.99 / $33.99",
    "image": "/image.png",
    "category": "Mandi",
    "diet": "SEAFOOD",
    "badge": "SEAFOOD",
    "dietColor": "#2563eb",
    "desc": "Whole coastal masala-fried fish served over Mandi rice with fresh lemon and chutney.",
    "spiceDefault": "Medium"
  },
  {
    "id": "fish-broaster-mandi",
    "name": "Fish Broaster Mandi",
    "price": "$16.99 / $24.99 / $32.99",
    "image": "https://images.unsplash.com/photo-1516714435131-44d6b64dc6a2?q=80&w=2070&auto=format&fit=crop",
    "category": "Mandi",
    "diet": "SEAFOOD",
    "badge": "SEAFOOD",
    "dietColor": "#2563eb",
    "desc": "Pressure-fried fish — crispy battered and golden — laid over fragrant Mandi rice.",
    "spiceDefault": "Medium"
  },
  {
    "id": "shrimp-tawa-fry-mandi",
    "name": "Shrimp Tawa Fry Mandi",
    "price": "$15.99 / $23.99 / $31.99",
    "image": "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=1974&auto=format&fit=crop",
    "category": "Mandi",
    "diet": "SEAFOOD",
    "badge": "SEAFOOD",
    "dietColor": "#2563eb",
    "desc": "Spiced tawa-seared shrimp over Mandi rice with a drizzle of coastal herb sauce.",
    "spiceDefault": "Medium"
  },
  {
    "id": "mixed-mandi-full",
    "name": "Mixed Mandi Full",
    "price": "$34.99",
    "image": "/order_biryani_premium.png",
    "category": "Mandi",
    "diet": "NON-VEG",
    "badge": "SIGNATURE",
    "dietColor": "#dc2626",
    "desc": "A curated combination of our best Mandi proteins over fragrant rice — the perfect mixed feast for two.",
    "spiceDefault": "Medium"
  },
  {
    "id": "sultan-s-mandi",
    "name": "Sultan's Mandi",
    "price": "$59.99",
    "image": "/mutton_dum_biryani_premium.png",
    "category": "Mandi",
    "diet": "NON-VEG",
    "badge": "SERVES 4-5",
    "dietColor": "#dc2626",
    "desc": "Lamb Shank, Tawa Fish Fry, Al-Faham Chicken, and Chicken Fry over Mandi rice. A royal spread.",
    "spiceDefault": "Medium"
  },
  {
    "id": "almas-majilis-mandi",
    "name": "Almas Majilis Mandi",
    "price": "$99.99",
    "image": "/tandoori_platter_premium.png",
    "category": "Mandi",
    "diet": "NON-VEG",
    "badge": "SERVES 7-8",
    "dietColor": "#dc2626",
    "desc": "2 Mutton, 2 Fish, 4 Chicken over unlimited Mandi rice — the ultimate communal feast.",
    "spiceDefault": "Medium"
  }
];
